// import '@/app/globals.css'

export const metadata = {
  title: '2024市川ゼミ_ラベリングツール',
  description: 'Generated by Next.js, Vercel',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  )
}
