export const test_table = [
  {
    number: 2,
    text: 'とりあえずヤマさんヤマさんから',
    speaker_code: 2,
    from: 3.52,
    to: 6.29999999999999,
    label: 0,
    new_label: 0,
  },
  {
    number: 3,
    text: '俺から行く？良いよ',
    speaker_code: 3,
    from: 6.3,
    to: 7.9,
    label: 2,
    new_label: 2,
  },
  {
    number: 4,
    text: 'ちょっと待ってね',
    speaker_code: 2,
    from: 7.9,
    to: 9.02,
    label: 0,
    new_label: 0,
  },
  {
    number: 5,
    text: 'まずこのタンジェント3乗xあるじゃんこれをコサインタンジェントxまずコサイン分のサインxってあるじゃないか？あるじゃん？',
    speaker_code: 3,
    from: 9.02,
    to: 15.26,
    label: 0,
    new_label: 0,
  },
  {
    number: 6,
    text: 'うんうん',
    speaker_code: 2,
    from: 15.26,
    to: 15.82,
    label: 5,
    new_label: 5,
  },
  {
    number: 7,
    text: 'あるじゃんでそれをまず分けるで3乗だから分けてこれ上が次サインが3乗だから3乗はまぁ嫌だから1個だけサインをはねのけて偶数乗にしといたほうが良いこっち側をで偶数乗だと1マイナスコサインxでコサインxが出るような形が作れるから',
    speaker_code: 3,
    from: 15.82,
    to: 29.14,
    label: 5,
    new_label: 5,
  },
  {
    number: 8,
    text: 'うんうん',
    speaker_code: 2,
    from: 29.14,
    to: 29.82,
    label: 7,
    new_label: 7,
  },
  {
    number: 9,
    text: '変えるサインはそのまま放置こっからもうやりたいのはカモネギ積分だからこれを微分する',
    speaker_code: 3,
    from: 29.82,
    to: 37.6,
    label: 7,
    new_label: 7,
  },
  {
    number: 10,
    text: '何で何でカモネギ積分やりたいの？',
    speaker_code: 1,
    from: 37.6,
    to: 39.28,
    label: 9,
    new_label: NaN,
  },
  {
    number: 11,
    text: 'コサインとコサインがあってサインだから明らかにサインをとりあえず微分すりゃコサインxだから',
    speaker_code: 3,
    from: 39.4,
    to: 44.53999999999999,
    label: 10,
    new_label: NaN,
  },
  {
    number: 12,
    text: 'あーそうかなるほどうんうんうん',
    speaker_code: 2,
    from: 44.54,
    to: 45.62,
    label: 11,
    new_label: NaN,
  },
  {
    number: 13,
    text: '微分って元がコサインxだからとりあえず絶対できるできるって確信があるからだからまず変えるマイナス出る理由はこれがこれ微分するとマイナスサインxだから合わせるこれを1個こっちにこれのマイナスをこっちにずらす',
    speaker_code: 3,
    from: 45.62,
    to: 57.74,
    label: 11,
    new_label: NaN,
  },
  {
    number: 14,
    text: 'うん',
    speaker_code: 2,
    from: 57.74,
    to: 57.94,
    label: 13,
    new_label: NaN,
  },
]
